---
# actual_value_idx - Index of the actual value
# actual_value - Actual value

- name: Compliance Audit | {{ redhat_7_baseline_key }} | Check if each expected value is in each actual value | Check if all values in expected values is in each actual value
  set_fact:
    redhat_7_audit_match_count: "{{ redhat_7_audit_match_count  | default(0) | int + 1 }}"
  when:
    - redhat_7_rules[redhat_7_rule_key]['actual_values'][actual_value_idx] | regex(value_item)
  loop: "{{ redhat_7_rules[redhat_7_rule_key]['expected_values'][actual_value_idx] }}"
  loop_control:
    loop_var: value_item