---
# Compliance audit - either_value_in_each_expected_value_is_in_each_actual_value #
##################################################################################
# redhat_7_rule_key - key of the rule
# redhat_7_baseline_key - key of the baseline being checked

- name: Compliance Audit | {{ redhat_7_baseline_key }} | Display current value of variables
  debug:
    msg: |-
      redhat_7_rule_key: {{ redhat_7_rule_key }}
      redhat_7_baseline_key: {{ redhat_7_baseline_key }}
    verbosity: 2

- name: Compliance Audit | {{ redhat_7_baseline_key }} | Set values for count variable
  set_fact:
    redhat_7_audit_match_count: 0

- name: Compliance Audit | {{ redhat_7_baseline_key }} | Check if each actual value is in each expected value
  set_fact:
    redhat_7_audit_match_count: "{{ redhat_7_audit_match_count  | default(0) | int + 1 }}"
  when: redhat_7_rules[redhat_7_rule_key]['actual_values'][expected_value_index] | regex(expected_value_item[0]) or redhat_7_rules[redhat_7_rule_key]['actual_values'][expected_value_index] | regex(expected_value_item[1])
  loop: "{{ redhat_7_rules[redhat_7_rule_key]['expected_values'] }}"
  loop_control:
    index_var: expected_value_index
    loop_var: expected_value_item

- name: Compliance Audit | {{ redhat_7_baseline_key }} | Mark as compliant
  set_fact:
    redhat_7_hardening_compliance_baseline_data: "{{ redhat_7_hardening_compliance_baseline_data | combine({redhat_7_baseline_key: {'compliance': 'C' }}, recursive=true) }}"
  when: redhat_7_audit_match_count | int == redhat_7_rules[redhat_7_rule_key]['expected_values'] | length

- name: Compliance Audit | {{ redhat_7_baseline_key }} | Display compliance
  debug:
    msg: |-
      Number of actual values and expected values matches: {{ redhat_7_audit_match_count }}
      Compliance: {{ redhat_7_hardening_compliance_baseline_data[redhat_7_baseline_key]['compliance'] }}
    verbosity: 2

- name: Risk Register Check | {{ redhat_7_baseline_key }}
  include_tasks: risk_register_check.yml
  vars:
    redhat_7_risk_register_rule_key: "{{ redhat_7_rule_key }}"
    redhat_7_risk_register_baseline_key: "{{ redhat_7_baseline_key }}"
  when:
    - redhat_7_hardening_compliance_baseline_data is defined
    - redhat_7_hardening_compliance_baseline_data[redhat_7_baseline_key]['compliance'] == 'NC'