---
# Compliance audit - redhat_7_keppel_10_1_contains #
###################################################
# redhat_7_rule_key - key of the rule
# redhat_7_baseline_key - key of the baseline being checked

- name: Compliance Audit | {{ redhat_7_baseline_key }} | Display current value of variables
  debug:
    msg: |-
      redhat_7_rule_key: {{ redhat_7_rule_key }}
      redhat_7_baseline_key: {{ redhat_7_baseline_key }}
    verbosity: 2

- name: Compliance Audit | {{ redhat_7_baseline_key }} | Set values for count variable
  set_fact:
    redhat_7_audit_match_count: 0

- name: Compliance Audit | {{ redhat_7_baseline_key }} | Check configuration
  set_fact:
    redhat_7_audit_match_count: "{{ redhat_7_audit_match_count  | default(0) | int + 1 }}"
  when:
    - redhat_7_rules[redhat_7_rule_key]['actual_values'][0] is defined
    - redhat_7_rules[redhat_7_rule_key]['expected_values'][0] is defined
    - redhat_7_rules[redhat_7_rule_key]['actual_values'][0] | regex(redhat_7_rules[redhat_7_rule_key]['expected_values'][0])

- name: Compliance Audit | {{ redhat_7_baseline_key }} | Check configuration per user
  set_fact:
    redhat_7_audit_match_count: "{{ redhat_7_audit_match_count  | default(0) | int + 1 }}"
  when:
    - redhat_7_rules[redhat_7_rule_key]['actual_values'][1] is defined
    - redhat_7_rules[redhat_7_rule_key]['expected_values'][1] is defined
    - user_configuration_item | regex(redhat_7_rules[redhat_7_rule_key]['expected_values'][1])
  loop: "{{ redhat_7_rules[redhat_7_rule_key]['actual_values'][1] }}"
  loop_control:
    loop_var: user_configuration_item

- name: Compliance Audit | {{ redhat_7_baseline_key }} | Mark as compliant
  set_fact:
    redhat_7_hardening_compliance_baseline_data: "{{ redhat_7_hardening_compliance_baseline_data | combine({redhat_7_baseline_key: {'compliance': 'C' }}, recursive=true) }}"
  when:
    - redhat_7_rules[redhat_7_rule_key]['actual_values'][1] is defined
    - redhat_7_audit_match_count | int == (redhat_7_rules[redhat_7_rule_key]['actual_values'][1] | length + 1)

- name: Compliance Audit | {{ redhat_7_baseline_key }} | Display compliance
  debug:
    msg: |-
      Number of actual values and expected values matches: {{ redhat_7_audit_match_count }}
      Compliance: {{ redhat_7_hardening_compliance_baseline_data[redhat_7_baseline_key]['compliance'] }}
    verbosity: 2