---
# Risk Register Check #
#######################
# redhat_7_risk_register_rule_key - key of the rule
# redhat_7_risk_register_baseline_key - key of the baseline being checked

- name: Risk Register Check | {{ redhat_7_risk_register_baseline_key }} | Display current value of variables
  debug:
    msg: |-
      redhat_7_risk_register_baseline_key: {{ redhat_7_risk_register_baseline_key }}
      redhat_7_risk_register_rule_key: {{ redhat_7_risk_register_rule_key }}
    verbosity: 2

- name: Risk Register Check | {{ redhat_7_risk_register_baseline_key }} | Set values for count variables
  set_fact:
    redhat_7_risk_register_match_count: 0

- name: Risk Register Check | {{ redhat_7_risk_register_baseline_key }} | Get accepted values from risk register
  set_fact:
    redhat_7_risk_register_accepted_values: "{{ redhat_7_risk_register[inventory_hostname][redhat_7_risk_register_baseline_key]['accepted_values'] }}"
  when:
    - redhat_7_risk_register[inventory_hostname] is defined
    - redhat_7_risk_register[inventory_hostname][redhat_7_risk_register_baseline_key] is defined
    - redhat_7_risk_register[inventory_hostname][redhat_7_risk_register_baseline_key]['accepted_values'] is defined

- name: Risk Register Check | {{ redhat_7_risk_register_baseline_key }} | Check if actual value/s are accepted in the risk register
  set_fact:
    redhat_7_risk_register_match_count: "{{ redhat_7_risk_register_match_count | default(0) | int + 1 }}"
  when:
    - redhat_7_risk_register_accepted_values is defined
    - redhat_7_risk_register_accepted_values[risk_register_actual_value_index] is defined
    - risk_register_actual_value_item == redhat_7_risk_register_accepted_values[risk_register_actual_value_index]
  loop: "{{ redhat_7_rules[redhat_7_risk_register_rule_key]['actual_values'] }}"
  loop_control:
    index_var: risk_register_actual_value_index
    loop_var: risk_register_actual_value_item

- name: Risk Register Check | {{ redhat_7_risk_register_baseline_key }} | Mark as risk accepted
  set_fact:
    redhat_7_hardening_compliance_baseline_data: "{{ redhat_7_hardening_compliance_baseline_data | combine({redhat_7_risk_register_baseline_key: {'compliance': 'RA' }}, recursive=true) }}"
  when:
    - redhat_7_risk_register_accepted_values is defined
    - redhat_7_risk_register_accepted_values | length == redhat_7_rules[redhat_7_risk_register_rule_key]['actual_values'] | length
    - redhat_7_risk_register_accepted_values | length == redhat_7_risk_register_match_count | int

- name: Risk Register Check | {{ redhat_7_risk_register_baseline_key }} | Display match count data
  debug:
    msg: |-
      Number of risk register accepted values: {{ redhat_7_risk_register_accepted_values | default([]) | length }}
      Number of actual values and risk register accepted values matches: {{ redhat_7_risk_register_match_count }}
    verbosity: 2