---
- name: Get compliance data from SUSE Linux 12 managed nodes
  hosts: suse_servers
  strategy: free
  ignore_errors: true
  ignore_unreachable: true
  become: yes
  roles:
    - suse_linux_12_hardening_compliance_data

- name: Check compliance of SUSE Linux 12 managed nodes
  hosts: suse_servers
  ignore_errors: true
  ignore_unreachable: true
  become: yes
  roles:
    - suse_linux_12_hardening_compliance_audit

- name: Generate SUSE Linux 12 hardening compliance report
  hosts: suse_servers
  ignore_errors: true
  ignore_unreachable: true
  roles:
    - suse_linux_12_hardening_compliance_report
