---

- name: Get compliance data from Redhat 7 managed nodes
  hosts: redhat_servers
  strategy: free
  ignore_errors: true
  ignore_unreachable: true
  become: yes
  roles:
    - redhat_7_hardening_compliance_data

- name: Check compliance of Redhat 7 managed nodes
  hosts: redhat_servers
  ignore_errors: true
  ignore_unreachable: true
  become: yes
  roles:
    - redhat_7_hardening_compliance_audit

- name: Generate Redhat 7 hardening compliance report
  hosts: redhat_servers
  ignore_errors: true
  ignore_unreachable: true
  roles:
    - redhat_7_hardening_compliance_report
