---
# Compliance audit - all_values_in_each_expected_value_is_in_each_actual_value #
################################################################################
# suse_12_rule_key - key of the rule
# suse_12_baseline_key - key of the baseline being checked

- name: Compliance Audit | {{ suse_12_baseline_key }} | Display current value of variables
  debug:
    msg: |-
      suse_12_rule_key: {{ suse_12_rule_key }}
      suse_12_baseline_key: {{ suse_12_baseline_key }}
    verbosity: 2

- name: Compliance Audit | {{ suse_12_baseline_key }} | Set values for count variable
  set_fact:
    suse_12_audit_match_count: 0

- name: Compliance Audit | {{ suse_12_baseline_key }} | Check if all values in each expected value is in each actual value
  include_tasks: actual_value_contains_all_values_in_expected_value.yml
  vars:
    actual_value_idx: "{{ actual_value_index }}"
    actual_value: "{{ actual_value_item }}"
  when:
    - suse_12_rules[suse_12_rule_key]['expected_values'] is defined
    - suse_12_rules[suse_12_rule_key]['expected_values'] | length
    - suse_12_rules[suse_12_rule_key]['expected_values'][actual_value_idx] is defined
    - suse_12_rules[suse_12_rule_key]['expected_values'][actual_value_idx] | length
  loop: "{{ suse_12_rules[suse_12_rule_key]['actual_values'] }}"
  loop_control:
    index_var: actual_value_index
    loop_var: actual_value_item

- name: Compliance Audit | {{ suse_12_baseline_key }} | Mark as compliant
  set_fact:
    suse_12_hardening_compliance_baseline_data: "{{ suse_12_hardening_compliance_baseline_data | combine({suse_12_baseline_key: {'compliance': 'C' }}, recursive=true) }}"
  when:
    - suse_12_rules[suse_12_rule_key]['expected_values'] is defined
    - suse_12_rules[suse_12_rule_key]['expected_values'] | length
    - suse_12_audit_match_count | int == lookup('flattened', suse_12_rules[suse_12_rule_key]['expected_values']) | length

- name: Compliance Audit | {{ suse_12_baseline_key }} | Display compliance
  debug:
    msg: |-
      Number of actual values and expected values matches: {{ suse_12_audit_match_count }}
      Compliance: {{ suse_12_hardening_compliance_baseline_data[suse_12_baseline_key]['compliance'] }}
    verbosity: 2

- name: Risk Register Check | {{ suse_12_baseline_key }}
  include_tasks: risk_register_check.yml
  vars:
    suse_12_risk_register_rule_key: "{{ suse_12_rule_key }}"
    suse_12_risk_register_baseline_key: "{{ suse_12_baseline_key }}"
  when:
    - suse_12_hardening_compliance_baseline_data is defined
    - suse_12_hardening_compliance_baseline_data[suse_12_baseline_key]['compliance'] == 'NC'
