---
# Set rule values #
###################
# redhat_7_cis_rule_key - key of the rule
# redhat_7_cis_rule_expected_values: list of expected values for the rule
# redhat_7_cis_rule_output - results of running the audit commands

- name: Set Rule Values | {{ redhat_7_cis_rule_key }} | Display current value of variables
  debug:
    msg: |-
      redhat_7_cis_rule_key: {{ redhat_7_cis_rule_key }}
      redhat_7_cis_rule_expected_values: {{ redhat_7_cis_rule_expected_values }}
      redhat_7_cis_rule_output: {{ redhat_7_cis_rule_output }}
    verbosity: 2

- name: Set Rule Values | {{ redhat_7_cis_rule_key }} | Set expected values
  set_fact:
    redhat_7_rules: "{{ redhat_7_rules | combine({redhat_7_cis_rule_key: {'expected_values': redhat_7_cis_rule_expected_values}}, recursive=true) }}"

- name: Set Rule Values | {{ redhat_7_cis_rule_key }} | Set actual values using results
  set_fact:
    redhat_7_rules: "{{ redhat_7_rules | combine({redhat_7_cis_rule_key: {'actual_values':  redhat_7_rules[redhat_7_cis_rule_key]['actual_values'] + [item['stderr'] if item['stderr']|length and item['rc']|int == 1 else item['stdout'] | trim] }}, recursive=true) }}"
  loop: "{{ redhat_7_cis_rule_output['results'] }}"
  when: redhat_7_cis_rule_output['results'] is defined

- name: Set Rule Values | {{ redhat_7_cis_rule_key }} | Set actual value
  set_fact:
    redhat_7_rules: "{{ redhat_7_rules | combine({redhat_7_cis_rule_key: {'actual_values':  redhat_7_rules[redhat_7_cis_rule_key]['actual_values'] + [redhat_7_cis_rule_output['stderr'] if redhat_7_cis_rule_output['stderr']|length and redhat_7_cis_rule_output['rc']|int == 1 else redhat_7_cis_rule_output['stdout'] | trim] }}, recursive=true) }}"
  when: redhat_7_cis_rule_output['results'] is not defined

- name: Set Rule Values | {{ redhat_7_cis_rule_key }} | Display rule values
  debug:
    msg: |-
      redhat_7_rules[{{ redhat_7_cis_rule_key }}]['expected_values']: {{ redhat_7_rules[redhat_7_cis_rule_key]['expected_values'] }}
      redhat_7_rules[{{ redhat_7_cis_rule_key }}]['actual_values']: {{ redhat_7_rules[redhat_7_cis_rule_key]['actual_values'] }}
    verbosity: 2
