---
- name: Import all configuration dictionaries
  include_vars:
    dir: vars/configuration

- name: Compliance Audit
  include_tasks: "{{ item['value']['compliance_audit'] }}"
  vars:
    redhat_7_rule_key: "{{ item['value']['rule'] }}"
    redhat_7_baseline_key: "{{ item['key'] }}"
  loop: "{{ lookup('dict', redhat_7_hardening_compliance_baseline_data) }}"
  loop_control:
    label: "redhat_7_{{ item['value']['rule'] }}: {{ item['key'] }}, {{ item['value']['rule'] }}"
  when:
    - redhat_7_hardening_compliance_baseline_data is defined
    - item['value']['compliance_audit'] is defined
    - item['value']['compliance_audit']

- name: Get a summary of compliance to the rules
  include_tasks: hardening_compliance_summary.yml
  vars:
    redhat_7_summary_baseline_key: "{{ item }}"
  loop: "{{ redhat_7_hardening_compliance_baseline }}"
  loop_control:
    label: "{{ item }}"
  when: redhat_7_hardening_compliance_baseline is defined