---
# Risk Register #
#################
# This is configured based on the client's risk register
# Contains a list of exceptions to rules
# First level key - hostname
# Second level key - baseline from dict "redhat_7_hardening_compliance_baseline_data"

# TODO: Configure according to site policy. Entries added are examples only
redhat_7_risk_register:
  REDHAT7:
    baseline_1_1_1_8:
      accepted_values:
        - |-
          insmod /lib/modules/3.10.0-1062.4.1.el7.x86_64/kernel/fs/fat/fat.ko.xz 
          insmod /lib/modules/3.10.0-1062.4.1.el7.x86_64/kernel/fs/fat/vfat.ko.xz
        - ""
      date_approved: 2019-10-30
      approved_by: Sample Approver

  REDHAT7-2:
    baseline_1_1_1_8:
      accepted_values:
        - |-
          insmod /lib/modules/3.10.0-1062.4.1.el7.x86_64/kernel/fs/fat/fat.ko.xz
          insmod /lib/modules/3.10.0-1062.4.1.el7.x86_64/kernel/fs/fat/vfat.ko.xz
        - ""
      date_approved: 2019-10-30
      approved_by: Sample Approver
