---
- name: Import all configuration dictionaries
  include_vars:
    dir: vars/configuration

- name: Compliance Audit
  include_tasks: "{{ item['value']['compliance_audit'] }}"
  vars:
    suse_12_rule_key: "{{ item['value']['rule'] }}"
    suse_12_baseline_key: "{{ item['key'] }}"
  loop: "{{ lookup('dict', suse_12_hardening_compliance_baseline_data) }}"
  loop_control:
    label: "suse_12_{{ item['value']['rule'] }}: {{ item['key'] }}, {{ item['value']['rule'] }}"
  when:
    - suse_12_hardening_compliance_baseline_data is defined
    - item['value']['compliance_audit'] is defined
    - item['value']['compliance_audit']

- name: Get a summary of compliance to the rules
  include_tasks: hardening_compliance_summary.yml
  vars:
    suse_12_summary_baseline_key: "{{ item }}"
  loop: "{{ suse_12_hardening_compliance_baseline }}"
  loop_control:
    label: "{{ item }}"
  when: suse_12_hardening_compliance_baseline is defined