---
- name: 1.3.1
  block:
    - name: 1.3.1 Ensure AIDE is installed
      shell: rpm -q aide
      register: redhat_7_cis_1_3_1_out      

    - name: 1.3.1 Ensure AIDE is installed | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_1_3_1"
        redhat_7_cis_rule_expected_values:
          - "aide"
        redhat_7_cis_rule_output: "{{ redhat_7_cis_1_3_1_out }}"
  ignore_errors: true
  when: redhat_7_cis_1_3_1 | bool

- name: 1.3.2
  block:
    - name: 1.3.2 Ensure filesystem integrity is regularly checked
      shell: grep -rh aide /etc/cron.* /etc/crontab
      register: redhat_7_cis_1_3_2_out

    - name: 1.3.2 Ensure filesystem integrity is regularly checked | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_1_3_2"
        redhat_7_cis_rule_expected_values:
          - "/usr/sbin/aide --check"
        redhat_7_cis_rule_output: "{{ redhat_7_cis_1_3_2_out }}"
  ignore_errors: true
  when: redhat_7_cis_1_3_2 | bool
