---
- name: 5.4.2
  block:
    - name: 5.4.2 Ensure system accounts are non-login
      shell: >-
        egrep -v "^\+" /etc/passwd | awk -F: '($1!="root" && $1!="sync" && $1!="shutdown" && $1!="halt" && $3<1000 && $7!="/sbin/nologin" && $7!="/bin/false") {print}'
      register: redhat_7_cis_5_4_2_out

    - name: 5.4.2 Ensure system accounts are non-login | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_5_4_2"
        redhat_7_cis_rule_expected_values:
          - ""
        redhat_7_cis_rule_output: "{{ redhat_7_cis_5_4_2_out }}"
  ignore_errors: true
  when: redhat_7_cis_5_4_2 | bool

- name: 5.4.3
  block:
    - name: 5.4.3 Ensure default group for the root account is GID 0
      shell: >-
        grep "^root:" /etc/passwd | cut -f4 -d:
      register: redhat_7_cis_5_4_3_out

    - name: 5.4.3 Ensure default group for the root account is GID 0 | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_5_4_3"
        redhat_7_cis_rule_expected_values:
          - "0"
        redhat_7_cis_rule_output: "{{ redhat_7_cis_5_4_3_out }}"
  ignore_errors: true
  when: redhat_7_cis_5_4_3 | bool

- name: 5.4.4
  block:
    - name: 5.4.4 Ensure default user umask is 027 or more restrictive
      shell: "{{ item }}"
      loop:
        - grep -w "umask 027" /etc/bashrc
        - grep -wh "umask 027" /etc/profile /etc/profile.d/*.sh
      register: redhat_7_cis_5_4_4_out

    - name: 5.4.4 Ensure default user umask is 027 or more restrictive | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_5_4_4"
        redhat_7_cis_rule_expected_values:
          - "umask 027"
          - "umask 027"
        redhat_7_cis_rule_output: "{{ redhat_7_cis_5_4_4_out }}"
  ignore_errors: true
  when: redhat_7_cis_5_4_4 | bool

- name: 5.6
  block:
    - name: 5.6 Ensure access to the su command is restricted
      shell: grep pam_wheel.so /etc/pam.d/su | grep -v ^#
      register: redhat_7_cis_5_6_out

    - name: 5.6 Ensure access to the su command is restricted | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_5_6"
        redhat_7_cis_rule_expected_values:
          - "auth           required        pam_wheel.so use_uid"
        redhat_7_cis_rule_output: "{{ redhat_7_cis_5_6_out }}"
  ignore_errors: true
  when: redhat_7_cis_5_6 | bool
