---
- name: 4.2.1.1
  block:
    - name: 4.2.1.1 Ensure rsyslog Service is enabled
      shell: systemctl is-enabled rsyslog
      register: redhat_7_cis_4_2_1_1_out

    - name:  4.2.1.1 Ensure rsyslog Service is enabled | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_4_2_1_1"
        redhat_7_cis_rule_expected_values:
          - "enabled"
        redhat_7_cis_rule_output: "{{ redhat_7_cis_4_2_1_1_out }}"
  ignore_errors: true
  when: redhat_7_cis_4_2_1_1 | bool

- name: 4.2.1.3
  block:
    - name: 4.2.1.3 Ensure rsyslog default file permissions configured
      shell: grep -h ^\$FileCreateMode /etc/rsyslog.conf /etc/rsyslog.d/*.conf | grep -v ^#
      register: redhat_7_cis_4_2_1_3_out

    - name: 4.2.1.3 Ensure rsyslog default file permissions configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_4_2_1_3"
        redhat_7_cis_rule_expected_values:
          - "$FileCreateMode 0640"
        redhat_7_cis_rule_output: "{{ redhat_7_cis_4_2_1_3_out }}"
  ignore_errors: true
  when: redhat_7_cis_4_2_1_3 | bool

- name: 4.2.1.4
  block:
    - name: 4.2.1.4 Ensure rsyslog is configured to send logs to a remote log host
      shell: grep "^*.*[^I][^I]*@" /etc/rsyslog.conf /etc/rsyslog.d/*.conf -h
      register: redhat_7_cis_4_2_1_4_out

    - name: 4.2.1.4 Ensure rsyslog is configured to send logs to a remote log host | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_4_2_1_4"
        redhat_7_cis_rule_expected_values:
          - "*.* @@10.58.98.84:514"
        redhat_7_cis_rule_output: "{{ redhat_7_cis_4_2_1_4_out }}"
  ignore_errors: true
  when: redhat_7_cis_4_2_1_4 | bool

- name: 4.2.3
  block:
    - name: 4.2.3 Ensure rsyslog or syslog-ng is installed
      shell: "{{ item }}"
      loop:
        - rpm -q rsyslog
        - rpm -q syslog-ng
      register: redhat_7_cis_4_2_3_out

    - name: 4.2.3 Ensure rsyslog or syslog-ng is installed | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_4_2_3"
        redhat_7_cis_rule_expected_values:
          - - "rsyslog"
            - package rsyslog is not installed
          - - "syslog-ng"
            - package syslog-ng is not installed
        redhat_7_cis_rule_output: "{{ redhat_7_cis_4_2_3_out }}"
  ignore_errors: true
  when: redhat_7_cis_4_2_3 | bool

- name: 4.2.4
  block:
    - name: 4.2.4 Ensure permissions on all logfiles are configured
      shell: find /var/log -type f -perm /g=wx -perm /o=rwx
      register: redhat_7_cis_4_2_4_out

    - name: 4.2.4 Ensure permissions on all logfiles are configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_4_2_4"
        redhat_7_cis_rule_expected_values:
          - ""
        redhat_7_cis_rule_output: "{{ redhat_7_cis_4_2_4_out }}"
  ignore_errors: true
  when: redhat_7_cis_4_2_4 | bool
