---
- name: 1.4.1
  block:
    - name: 1.4.1 Ensure permissions on bootloader config are configured
      shell: stat /boot/grub2/grub.cfg -c "%a %U %G"
      register: redhat_7_cis_1_4_1_out

    - name: 1.4.1 Ensure permissions on bootloader config are configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_1_4_1"
        redhat_7_cis_rule_expected_values:
          - "600 root root"
        redhat_7_cis_rule_output: "{{ redhat_7_cis_1_4_1_out }}"
  ignore_errors: true
  when: redhat_7_cis_1_4_1 | bool

- name: 1.4.2
  block:
    - name: 1.4.2 Ensure bootloader password is set
      shell: grep "^GRUB2_PASSWORD" /boot/grub2/grub.cfg
      register: redhat_7_cis_1_4_2_out

    - name: 1.4.2 Ensure bootloader password is set | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_1_4_2"
        redhat_7_cis_rule_expected_values:
          - "GRUB2_PASSWORD"
        redhat_7_cis_rule_output: "{{ redhat_7_cis_1_4_2_out }}"
  ignore_errors: true
  when: redhat_7_cis_1_4_2 | bool

- name: 1.4.3
  block:
    - name: 1.4.3 Ensure authentication required for single user mode
      shell: "{{ item }}"
      loop:
        - grep /sbin/sulogin /usr/lib/systemd/system/rescue.service
        - grep /sbin/sulogin /usr/lib/systemd/system/emergency.service
      register: redhat_7_cis_1_4_3_out

    - name: 1.4.3 Ensure authentication required for single user mode | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_1_4_3"
        redhat_7_cis_rule_expected_values:
          - "/usr/sbin/sulogin"
          - "/usr/sbin/sulogin"
        redhat_7_cis_rule_output: "{{ redhat_7_cis_1_4_3_out }}"
  ignore_errors: true
  when: redhat_7_cis_1_4_3 | bool
