---
- name: 3.6.1
  block:
    - name: Ensure iptables is installed
      shell: rpm -q iptables
      register: redhat_7_cis_3_6_1_out      

    - name: 3.6.1 Ensure iptables is installed | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_3_6_1"
        redhat_7_cis_rule_expected_values:
          - "iptables"
        redhat_7_cis_rule_output: "{{ redhat_7_cis_3_6_1_out }}"
  ignore_errors: true
  when: redhat_7_cis_3_6_1 | bool
