---
- name: 2.3.1
  block:
    - name: 2.3.1 Ensure NIS Client is not installed
      shell: rpm -q ypbind
      register: redhat_7_cis_2_3_1_out

    - name: 2.3.1 Ensure NIS Client is not installed | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_2_3_1"
        redhat_7_cis_rule_expected_values:
          - package ypbind is not installed
        redhat_7_cis_rule_output: "{{ redhat_7_cis_2_3_1_out }}"
  ignore_errors: true
  when: redhat_7_cis_2_3_2 | bool

- name: 2.3.2
  block:
    - name: 2.3.2 Ensure rsh client is not installed
      shell: rpm -q rsh
      register: redhat_7_cis_2_3_2_out

    - name: 2.3.2 Ensure rsh client is not installed | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_2_3_2"
        redhat_7_cis_rule_expected_values:
          - package rsh is not installed
        redhat_7_cis_rule_output: "{{ redhat_7_cis_2_3_2_out }}"
  ignore_errors: true
  when: redhat_7_cis_2_3_2 | bool

- name: 2.3.3
  block:
    - name: 2.3.3 Ensure talk client is not installed
      shell: rpm -q talk
      register: redhat_7_cis_2_3_3_out

    - name: 2.3.3 Ensure talk client is not installed | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_2_3_3"
        redhat_7_cis_rule_expected_values:
          - package talk is not installed
        redhat_7_cis_rule_output: "{{ redhat_7_cis_2_3_3_out }}"
  ignore_errors: true
  when: redhat_7_cis_2_3_3 | bool

- name: 2.3.4
  block:
    - name: 2.3.4 Ensure telnet client is not installed
      shell: rpm -q telnet
      register: redhat_7_cis_2_3_4_out

    - name: 2.3.4 Ensure telnet client is not installed | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_2_3_4"
        redhat_7_cis_rule_expected_values:
          - package telnet is not installed
        redhat_7_cis_rule_output: "{{ redhat_7_cis_2_3_4_out }}"
  ignore_errors: true
  when: redhat_7_cis_2_3_4 | bool

- name: 2.3.5
  block:
    - name: 2.3.5 Ensure LDAP client is not installed
      shell: rpm -q openldap-clients
      register: redhat_7_cis_2_3_5_out

    - name: 2.3.5 Ensure LDAP client is not installed | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_2_3_5"
        redhat_7_cis_rule_expected_values:
          - package openldap-clients is not installed
        redhat_7_cis_rule_output: "{{ redhat_7_cis_2_3_5_out }}"
  ignore_errors: true
  when: redhat_7_cis_2_3_5 | bool

