---
- name: 1.5.1
  block:
    - name: 1.5.1 Ensure core dumps are restricted
      shell: "{{ item }}"
      loop:
        - egrep "\*\s+hard\s+core\s+0" /etc/security/limits.conf
        - sysctl fs.suid_dumpable 
        - grep "fs\.suid_dumpable" /etc/sysctl.conf
      register: redhat_7_cis_1_5_1_out

    - name: 1.5.1 Ensure core dumps are restricted | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_1_5_1"
        redhat_7_cis_rule_expected_values:
          - "{{ redhat_7_cis_1_5_1_expected_value }}"
          - "fs.suid_dumpable = 0"
          - "fs.suid_dumpable = 0"
        redhat_7_cis_rule_output: "{{ redhat_7_cis_1_5_1_out }}"
  ignore_errors: true
  when: redhat_7_cis_1_5_1 | bool

- name: 1.5.2
  block:
    - name: 1.5.2 Ensure XD/NX support is enabled
      shell: dmesg | grep -w NX | cut -d " " -f 6-
      register: redhat_7_cis_1_5_2_out

    - name: 1.5.2 Ensure XD/NX support is enabled | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_1_5_2"
        redhat_7_cis_rule_expected_values:
          - "NX (Execute Disable) protection: active"
        redhat_7_cis_rule_output: "{{ redhat_7_cis_1_5_2_out }}"
  ignore_errors: true
  when: redhat_7_cis_1_5_2 | bool

- name: 1.5.3
  block:
    - name: 1.5.3 Ensure address space layout randomization (ASLR) is enabled
      shell: "{{ item }}"
      loop:
        - sysctl kernel.randomize_va_space
        - grep "kernel\.randomize_va_space" /etc/sysctl.conf
      register: redhat_7_cis_1_5_3_out

    - name: 1.5.3 Ensure address space layout randomization (ASLR) is enabled | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_1_5_3"
        redhat_7_cis_rule_expected_values:
          - kernel.randomize_va_space = 2
          - kernel.randomize_va_space = 2
        redhat_7_cis_rule_output: "{{ redhat_7_cis_1_5_3_out }}"
  ignore_errors: true
  when: redhat_7_cis_1_5_3 | bool

- name: 1.5.4
  block:
    - name: 1.5.4 Ensure prelink is disabled
      shell: rpm -q prelink
      register: redhat_7_cis_1_5_4_out

    - name: 1.5.4 Ensure prelink is disabled | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_1_5_4"
        redhat_7_cis_rule_expected_values:
          - package prelink is not installed
        redhat_7_cis_rule_output: "{{ redhat_7_cis_1_5_4_out }}"
  ignore_errors: true
  when: redhat_7_cis_1_5_4 | bool
