---
- name: 3.5.1
  block:
    - name: 3.5.1 Ensure DCCP is disabled
      shell: "{{ item }}"
      loop:
        - modprobe -n -v -s dccp
        - lsmod | grep dccp
      register: redhat_7_cis_3_5_1_out

    - name: 3.5.1 Ensure DCCP is disabled | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_3_5_1"
        redhat_7_cis_rule_expected_values:
          - "install /bin/true"
          - ""
        redhat_7_cis_rule_output: "{{ redhat_7_cis_3_5_1_out }}"
  ignore_errors: true
  when: redhat_7_cis_3_5_1 | bool

- name: 3.5.2
  block:
    - name: 3.5.2 Ensure SCTP is disabled
      shell: "{{ item }}"
      loop:
        - modprobe -n -v -s sctp
        - lsmod | grep sctp
      register: redhat_7_cis_3_5_2_out

    - name: 3.5.2 Ensure SCTP is disabled | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_3_5_2"
        redhat_7_cis_rule_expected_values:
          - "install /bin/true"
          - ""
        redhat_7_cis_rule_output: "{{ redhat_7_cis_3_5_2_out }}"
  ignore_errors: true
  when: redhat_7_cis_3_5_2 | bool

- name: 3.5.3
  block:
    - name: 3.5.3 Ensure RDS is disabled
      shell: "{{ item }}"
      loop:
        - modprobe -n -v -s rds
        - lsmod | grep rds
      register: redhat_7_cis_3_5_3_out

    - name: 3.5.3 Ensure RDS is disabled | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_3_5_3"
        redhat_7_cis_rule_expected_values:
          - "install /bin/true"
          - ""
        redhat_7_cis_rule_output: "{{ redhat_7_cis_3_5_3_out }}"
  ignore_errors: true
  when: redhat_7_cis_3_5_3 | bool

- name: 3.5.4
  block:
    - name: 3.5.4 Ensure TIPC is disabled
      shell: "{{ item }}"
      loop:
        - modprobe -n -v -s tipc
        - lsmod | grep tipc
      register: redhat_7_cis_3_5_4_out

    - name: 3.5.4 Ensure TIPC is disabled | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_3_5_4"
        redhat_7_cis_rule_expected_values:
          - "install /bin/true"
          - ""
        redhat_7_cis_rule_output: "{{ redhat_7_cis_3_5_4_out }}"
  ignore_errors: true
  when: redhat_7_cis_3_5_4 | bool

