---
- name: 3.2.1
  block:
    - name: 3.2.1 Ensure source routed packets are not accepted
      shell: "{{ item }}"
      loop:
        - sysctl net.ipv4.conf.all.accept_source_route
        - sysctl net.ipv4.conf.default.accept_source_route
        - grep "net\.ipv4\.conf\.all\.accept_source_route" /etc/sysctl.conf
        - grep "net\.ipv4\.conf\.default\.accept_source_route" /etc/sysctl.conf
      register: redhat_7_cis_3_2_1_out

    - name: 3.2.1 Ensure source routed packets are not accepted | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_3_2_1"
        redhat_7_cis_rule_expected_values:
          - net.ipv4.conf.all.accept_source_route = 0
          - net.ipv4.conf.default.accept_source_route = 0
          - net.ipv4.conf.all.accept_source_route = 0
          - net.ipv4.conf.default.accept_source_route = 0
        redhat_7_cis_rule_output: "{{ redhat_7_cis_3_2_1_out }}"
  ignore_errors: true
  when: redhat_7_cis_3_2_1 | bool

- name: 3.2.2
  block:
    - name: 3.2.2 Ensure ICMP redirects are not accepted
      shell: "{{ item }}"
      loop:
        - sysctl net.ipv4.conf.all.accept_redirects
        - sysctl net.ipv4.conf.default.accept_redirects
        - grep "net\.ipv4\.conf\.all\.accept_redirects" /etc/sysctl.conf
        - grep "net\.ipv4\.conf\.default\.accept_redirects" /etc/sysctl.conf
      register: redhat_7_cis_3_2_2_out

    - name: 3.2.2 Ensure ICMP redirects are not accepted | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_3_2_2"
        redhat_7_cis_rule_expected_values:
          - net.ipv4.conf.all.accept_redirects = 0
          - net.ipv4.conf.default.accept_redirects = 0
          - net.ipv4.conf.all.accept_redirects = 0
          - net.ipv4.conf.default.accept_redirects = 0
        redhat_7_cis_rule_output: "{{ redhat_7_cis_3_2_2_out }}"
  ignore_errors: true
  when: redhat_7_cis_3_2_2 | bool

- name: 3.2.3
  block:
    - name: 3.2.3 Ensure secure ICMP redirects are not accepted
      shell: "{{ item }}"
      loop:
        - sysctl net.ipv4.conf.all.secure_redirects
        - sysctl net.ipv4.conf.default.secure_redirects
        - grep "net\.ipv4\.conf\.all\.secure_redirects" /etc/sysctl.conf
        - grep "net\.ipv4\.conf\.default\.secure_redirects" /etc/sysctl.conf
      register: redhat_7_cis_3_2_3_out

    - name: 3.2.3 Ensure secure ICMP redirects are not accepted | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_3_2_3"
        redhat_7_cis_rule_expected_values:
          - net.ipv4.conf.all.secure_redirects = 0
          - net.ipv4.conf.default.secure_redirects = 0
          - net.ipv4.conf.all.secure_redirects = 0
          - net.ipv4.conf.default.secure_redirects = 0
        redhat_7_cis_rule_output: "{{ redhat_7_cis_3_2_3_out }}"
  ignore_errors: true
  when: redhat_7_cis_3_2_3 | bool

- name: 3.2.4
  block:
    - name: 3.2.4 Ensure suspicious packets are logged
      shell: "{{ item }}"
      loop:
        - sysctl net.ipv4.conf.all.log_martians
        - sysctl net.ipv4.conf.default.log_martians
        - grep "net\.ipv4\.conf\.all\.log_martians" /etc/sysctl.conf
        - grep "net\.ipv4\.conf\.default\.log_martians" /etc/sysctl.conf 
      register: redhat_7_cis_3_2_4_out

    - name: 3.2.4 Ensure suspicious packets are logged | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_3_2_4"
        redhat_7_cis_rule_expected_values:
          - net.ipv4.conf.all.log_martians = 1
          - net.ipv4.conf.default.log_martians = 1
          - net.ipv4.conf.all.log_martians = 1
          - net.ipv4.conf.default.log_martians = 1 
        redhat_7_cis_rule_output: "{{ redhat_7_cis_3_2_4_out }}"
  ignore_errors: true
  when: redhat_7_cis_3_2_4 | bool

- name: 3.2.5
  block:
    - name: 3.2.5 Ensure broadcast ICMP requests are ignored
      shell: "{{ item }}"
      loop:
        - sysctl net.ipv4.icmp_echo_ignore_broadcasts
        - grep "net\.ipv4\.icmp_echo_ignore_broadcasts" /etc/sysctl.conf
      register: redhat_7_cis_3_2_5_out

    - name: 3.2.5 Ensure broadcast ICMP requests are ignored | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_3_2_5"
        redhat_7_cis_rule_expected_values:
          - net.ipv4.icmp_echo_ignore_broadcasts = 1
          - net.ipv4.icmp_echo_ignore_broadcasts = 1 
        redhat_7_cis_rule_output: "{{ redhat_7_cis_3_2_5_out }}"
  ignore_errors: true
  when: redhat_7_cis_3_2_5 | bool

- name: 3.2.6
  block:
    - name: 3.2.6 Ensure bogus ICMP responses are ignored
      shell: "{{ item }}"
      loop:
        - sysctl net.ipv4.icmp_ignore_bogus_error_responses
        - grep "net\.ipv4\.icmp_ignore_bogus_error_responses" /etc/sysctl.conf
      register: redhat_7_cis_3_2_6_out

    - name: 3.2.6 Ensure bogus ICMP responses are ignored | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_3_2_6"
        redhat_7_cis_rule_expected_values:
          - net.ipv4.icmp_ignore_bogus_error_responses = 1
          - net.ipv4.icmp_ignore_bogus_error_responses = 1 
        redhat_7_cis_rule_output: "{{ redhat_7_cis_3_2_6_out }}"
  ignore_errors: true
  when: redhat_7_cis_3_2_6 | bool

- name: 3.2.7
  block:
    - name: 3.2.7 Ensure Reverse Path Filtering is enabled
      shell: "{{ item }}"
      loop:
        - sysctl net.ipv4.conf.all.rp_filter
        - sysctl net.ipv4.conf.default.rp_filter
        - grep "net\.ipv4\.conf\.all\.rp_filter" /etc/sysctl.conf
        - grep "net\.ipv4\.conf\.default\.rp_filter" /etc/sysctl.conf
      register: redhat_7_cis_3_2_7_out

    - name: 3.2.7 Ensure Reverse Path Filtering is enabled | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_3_2_7"
        redhat_7_cis_rule_expected_values:
          - net.ipv4.conf.all.rp_filter = 1
          - net.ipv4.conf.default.rp_filter = 1
          - net.ipv4.conf.all.rp_filter = 1
          - net.ipv4.conf.default.rp_filter = 1
        redhat_7_cis_rule_output: "{{ redhat_7_cis_3_2_7_out }}"
  ignore_errors: true
  when: redhat_7_cis_3_2_7 | bool

- name: 3.2.8
  block:
    - name: 3.2.8 Ensure TCP SYN Cookies is enabled
      shell: "{{ item }}"
      loop:
        - sysctl net.ipv4.tcp_syncookies
        - grep "net\.ipv4\.tcp_syncookies" /etc/sysctl.conf
      register: redhat_7_cis_3_2_8_out

    - name: 3.2.8 Ensure TCP SYN Cookies is enabled | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_3_2_8"
        redhat_7_cis_rule_expected_values:
          - net.ipv4.tcp_syncookies = 1
          - net.ipv4.tcp_syncookies = 1
        redhat_7_cis_rule_output: "{{ redhat_7_cis_3_2_8_out }}"
  ignore_errors: true
  when: redhat_7_cis_3_2_8 | bool
