---
- name: 3.1.1
  block:
    - name: 3.1.1 Ensure IP forwarding is disabled
      shell: "{{ item }}"
      loop:
        - sysctl net.ipv4.ip_forward
        - grep "net\.ipv4\.ip_forward" /etc/sysctl.conf
      register: redhat_7_cis_3_1_1_out

    - name: 3.1.1 Ensure IP forwarding is disabled | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_3_1_1"
        redhat_7_cis_rule_expected_values:
          - "net.ipv4.ip_forward = 0"
          - "net.ipv4.ip_forward = 0"
        redhat_7_cis_rule_output: "{{ redhat_7_cis_3_1_1_out }}"
  ignore_errors: true
  when: redhat_7_cis_3_1_1 | bool
- name: 3.1.2
  block:
    - name: 3.1.2 Ensure packet redirect sending is disabled
      shell: "{{ item }}"
      loop:
        - sysctl net.ipv4.conf.all.send_redirects
        - sysctl net.ipv4.conf.default.send_redirects
        - grep "net\.ipv4\.conf\.all\.send_redirects" /etc/sysctl.conf
        - grep "net\.ipv4\.conf\.default\.send_redirects" /etc/sysctl.conf
      register: redhat_7_cis_3_1_2_out

    - name: 3.1.2 Ensure packet redirect sending is disabled | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_3_1_2"
        redhat_7_cis_rule_expected_values:
          - "net.ipv4.conf.all.send_redirects = 0"
          - "net.ipv4.conf.default.send_redirects = 0"
          - "net.ipv4.conf.all.send_redirects = 0"
          - "net.ipv4.conf.default.send_redirects = 0"
        redhat_7_cis_rule_output: "{{ redhat_7_cis_3_1_2_out }}"
  ignore_errors: true
  when: redhat_7_cis_3_1_2 | bool

