---
- name: 1.1.3
  block:
    - name: 1.1.3 Ensure nodev option set on /tmp partition
      shell: mount | grep /tmp | grep nodev
      register: redhat_7_cis_1_1_3_out      

    - name: 1.1.3 Ensure nodev option set on /tmp partition | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_1_1_3"
        redhat_7_cis_rule_expected_values:
          - "nodev"
        redhat_7_cis_rule_output: "{{ redhat_7_cis_1_1_3_out }}"
  ignore_errors: true
  when: redhat_7_cis_1_1_3 | bool

- name: 1.1.4
  block:
    - name: 1.1.4 Ensure nosuid option set on /tmp partition
      shell: mount | grep /tmp | grep nosuid
      register: redhat_7_cis_1_1_4_out

    - name: 1.1.4 Ensure nosuid option set on /tmp partition | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_1_1_4"
        redhat_7_cis_rule_expected_values:
          - "nosuid"
        redhat_7_cis_rule_output: "{{ redhat_7_cis_1_1_4_out }}"
  ignore_errors: true
  when: redhat_7_cis_1_1_4 | bool

- name: 1.1.5
  block:
    - name: 1.1.5 Ensure noexec option set on /tmp partition
      shell: mount | grep /tmp | grep noexec
      register: redhat_7_cis_1_1_5_out

    - name: 1.1.5 Ensure noexec option set on /tmp partition | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_1_1_5"
        redhat_7_cis_rule_expected_values:
          - "noexec"
        redhat_7_cis_rule_output: "{{ redhat_7_cis_1_1_5_out }}"
  ignore_errors: true
  when: redhat_7_cis_1_1_5 | bool

- name: 1.1.8
  block:
    - name: 1.1.8 Ensure nodev option set on /var/tmp partition
      shell: mount | grep /var/tmp | grep nodev
      register: redhat_7_cis_1_1_8_out

    - name: 1.1.8 Ensure nodev option set on /var/tmp partition | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_1_1_8"
        redhat_7_cis_rule_expected_values:
          - "nodev"
        redhat_7_cis_rule_output: "{{ redhat_7_cis_1_1_8_out }}"
  ignore_errors: true
  when: redhat_7_cis_1_1_8 | bool

- name: 1.1.9
  block:
    - name: 1.1.9 Ensure nosuid option set on /var/tmp partition
      shell: mount | grep /var/tmp | grep nosuid
      register: redhat_7_cis_1_1_9_out

    - name: 1.1.9 Ensure nosuid option set on /var/tmp partition | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_1_1_9"
        redhat_7_cis_rule_expected_values:
          - "nosuid"
        redhat_7_cis_rule_output: "{{ redhat_7_cis_1_1_9_out }}"
  ignore_errors: true
  when: redhat_7_cis_1_1_9 | bool

- name: 1.1.10
  block:
    - name: 1.1.10 Ensure noexec option set on /var/tmp partition
      shell: mount | grep /var/tmp | grep noexec
      register: redhat_7_cis_1_1_10_out

    - name: 1.1.10 Ensure noexec option set on /var/tmp partition | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_1_1_10"
        redhat_7_cis_rule_expected_values:
          - "noexec"
        redhat_7_cis_rule_output: "{{ redhat_7_cis_1_1_10_out }}"
  ignore_errors: true
  when: redhat_7_cis_1_1_10 | bool

- name: 1.1.14
  block:
    - name: 1.1.14 Ensure nodev option set on /home partition
      shell: mount | grep /home | grep nodev
      register: redhat_7_cis_1_1_14_out

    - name: 1.1.14 Ensure nodev option set on /home partition | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_1_1_14"
        redhat_7_cis_rule_expected_values:
          - "noexec"
        redhat_7_cis_rule_output: "{{ redhat_7_cis_1_1_14_out }}"
  ignore_errors: true
  when: redhat_7_cis_1_1_14 | bool

- name: 1.1.15
  block:
    - name: 1.1.15 Ensure nodev option set on /dev/shm partition
      shell: mount | grep /dev/shm | grep nodev
      register: redhat_7_cis_1_1_15_out

    - name: 1.1.15 Ensure nodev option set on /dev/shm partition | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_1_1_15"
        redhat_7_cis_rule_expected_values:
          - "nodev"
        redhat_7_cis_rule_output: "{{ redhat_7_cis_1_1_15_out }}"
  ignore_errors: true
  when: redhat_7_cis_1_1_15 | bool

- name: 1.1.16
  block:
    - name: 1.1.16 Ensure nosuid option set on /dev/shm partition
      shell: mount | grep /dev/shm | grep nosuid
      register: redhat_7_cis_1_1_16_out

    - name: 1.1.16 Ensure nosuid option set on /dev/shm partition | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_1_1_16"
        redhat_7_cis_rule_expected_values:
          - "nosuid"
        redhat_7_cis_rule_output: "{{ redhat_7_cis_1_1_16_out }}"
  ignore_errors: true
  when: redhat_7_cis_1_1_16 | bool

- name: 1.1.17
  block:
    - name: 1.1.17 Ensure noexec option set on /dev/shm partition
      shell: mount | grep /dev/shm | grep noexec
      register: redhat_7_cis_1_1_17_out

    - name: 1.1.17 Ensure noexec option set on /dev/shm partition | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_1_1_17"
        redhat_7_cis_rule_expected_values:
          - "noexec"
        redhat_7_cis_rule_output: "{{ redhat_7_cis_1_1_17_out }}"
  ignore_errors: true
  when: redhat_7_cis_1_1_17 | bool

- name: 1.1.21
  block:
    - name: 1.1.21 Ensure sticky bit is set on all world-writable directories
      shell: >-
        df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d \( -perm -0002 -a ! -perm -1000 \) 2>/dev/null
      register: redhat_7_cis_1_1_21_out

    - name: 1.1.21 Ensure sticky bit is set on all world-writable directories | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_1_1_21"
        redhat_7_cis_rule_expected_values:
          - ""
        redhat_7_cis_rule_output: "{{ redhat_7_cis_1_1_21_out }}"
  ignore_errors: true
  when: redhat_7_cis_1_1_21 | bool

- name: 1.1.22
  block:
    - name: 1.1.22 Disable Automounting
      shell: systemctl is-enabled autofs
      register: redhat_7_cis_1_1_22_out      

    - name: 1.1.22 Disable Automounting | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        redhat_7_cis_rule_key: "cis_1_1_22"
        redhat_7_cis_rule_expected_values:
         - - disabled
           - Failed to get unit file state
        redhat_7_cis_rule_output: "{{ redhat_7_cis_1_1_22_out }}"
  ignore_errors: true
  when: redhat_7_cis_1_1_22 | bool
