---
- name: 3.5.1
  block:
    - name: 3.5.1 Ensure DCCP is disabled
      shell: "{{ item }}"
      loop:
        - modprobe -n -v dccp
        - lsmod | grep dccp
      register: suse_12_cis_3_5_1_out

    - name: 3.5.1 Ensure DCCP is disabled | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_3_5_1"
        suse_12_cis_rule_expected_values:
          - "install /bin/true"
          - ""
        suse_12_cis_rule_output: "{{ suse_12_cis_3_5_1_out }}"
  ignore_errors: true
  when: suse_12_cis_3_5_1 | bool

- name: 3.5.2
  block:
    - name: 3.5.2 Ensure SCTP is disabled
      shell: "{{ item }}"
      loop:
        - modprobe -n -v sctp
        - lsmod | grep sctp
      register: suse_12_cis_3_5_2_out

    - name: 3.5.2 Ensure SCTP is disabled | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_3_5_2"
        suse_12_cis_rule_expected_values:
          - "install /bin/true"
          - ""
        suse_12_cis_rule_output: "{{ suse_12_cis_3_5_2_out }}"
  ignore_errors: true
  when: suse_12_cis_3_5_2 | bool

- name: 3.5.3
  block:
    - name: 3.5.3 Ensure RDS is disabled
      shell: "{{ item }}"
      loop:
        - modprobe -n -v rds
        - lsmod | grep rds
      register: suse_12_cis_3_5_3_out

    - name: 3.5.3 Ensure RDS is disabled | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_3_5_3"
        suse_12_cis_rule_expected_values:
          - "install /bin/true"
          - ""
        suse_12_cis_rule_output: "{{ suse_12_cis_3_5_3_out }}"
  ignore_errors: true
  when: suse_12_cis_3_5_3 | bool

- name: 3.5.4
  block:
    - name: 3.5.4 Ensure TIPC is disabled
      shell: "{{ item }}"
      loop:
        - modprobe -n -v tipc
        - lsmod | grep tipc
      register: suse_12_cis_3_5_4_out

    - name: 3.5.4 Ensure TIPC is disabled | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_3_5_4"
        suse_12_cis_rule_expected_values:
          - "install /bin/true"
          - ""
        suse_12_cis_rule_output: "{{ suse_12_cis_3_5_4_out }}"
  ignore_errors: true
  when: suse_12_cis_3_5_4 | bool

