---
- name: 3.1.1
  block:
    - name: 3.1.1 Ensure IP forwarding is disabled
      shell: "{{ item }}"
      loop:
        - sysctl net.ipv4.ip_forward | sed -e 's/ //g'
        - grep "net\.ipv4\.ip_forward" /etc/sysctl.conf | sed -e 's/ //g'
      register: suse_12_cis_3_1_1_out

    - name: 3.1.1 Ensure IP forwarding is disabled | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_3_1_1"
        suse_12_cis_rule_expected_values:
          - "net.ipv4.ip_forward=0"
          - "net.ipv4.ip_forward=0"
        suse_12_cis_rule_output: "{{ suse_12_cis_3_1_1_out }}"
  ignore_errors: true
  when: suse_12_cis_3_1_1 | bool