---
- name: 6.1.1
  block:
    - name: 6.1.1 Audit system file permissions
      shell: rpm -Va --nomtime --nosize --nomd5 --nolinkto
      register: suse_12_cis_6_1_1_out

    - name: 6.1.1 Audit system file permissions | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_6_1_1"
        suse_12_cis_rule_expected_values:
          - ""
        suse_12_cis_rule_output: "{{ suse_12_cis_6_1_1_out }}"
  ignore_errors: true
  when: suse_12_cis_6_1_1 | bool

- name: 6.1.2
  block:
    - name: 6.1.2 Ensure permissions on /etc/passwd are configured
      shell: stat /etc/passwd -c "%a %U %G"
      register: suse_12_cis_6_1_2_out

    - name: 6.1.2 Ensure permissions on /etc/passwd are configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_6_1_2"
        suse_12_cis_rule_expected_values:
          - "644 root root"
        suse_12_cis_rule_output: "{{ suse_12_cis_6_1_2_out }}"
  ignore_errors: true
  when: suse_12_cis_6_1_2 | bool

- name: 6.1.3
  block:
    - name: 6.1.3 Ensure permissions on /etc/shadow are configured
      shell: stat /etc/shadow -c "%a %U %G"
      register: suse_12_cis_6_1_3_out

    - name: 6.1.3 Ensure permissions on /etc/shadow are configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_6_1_3"
        suse_12_cis_rule_expected_values:
          - "640 root root"
        suse_12_cis_rule_output: "{{ suse_12_cis_6_1_3_out }}"
  ignore_errors: true
  when: suse_12_cis_6_1_3 | bool

- name: 6.1.4
  block:
    - name: 6.1.4 Ensure permissions on /etc/group are configured
      shell: stat /etc/group -c "%a %U %G"
      register: suse_12_cis_6_1_4_out

    - name: 6.1.4 Ensure permissions on /etc/group are configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_6_1_4"
        suse_12_cis_rule_expected_values:
          - "644 root root"
        suse_12_cis_rule_output: "{{ suse_12_cis_6_1_4_out }}"
  ignore_errors: true
  when: suse_12_cis_6_1_4 | bool

- name: 6.1.10
  block:
    - name: 6.1.10 Ensure no world writable files exist
      shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type f -perm -0002
      register: suse_12_cis_6_1_10_out

    - name: 6.1.10 Ensure no world writable files exist | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_6_1_10"
        suse_12_cis_rule_expected_values:
          - ""
        suse_12_cis_rule_output: "{{ suse_12_cis_6_1_10_out }}"
  ignore_errors: true
  when: suse_12_cis_6_1_10 | bool
