---
- name: 5.4.1.4
  block:
    - name: 5.4.1.4 Ensure inactive password lock is 30 days or less
      shell: useradd -D | grep INACTIVE
      register: suse_12_cis_5_4_1_4_out

    - name: 5.4.1.4 Ensure inactive password lock is 30 days or less | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_5_4_1_4"
        suse_12_cis_rule_expected_values:
          - "INACTIVE=30"
        suse_12_cis_rule_output: "{{ suse_12_cis_5_4_1_4_out }}"
  ignore_errors: true
  when: suse_12_cis_5_4_1_4 | bool