---
- name: 6.2.1
  block:
    - name: 6.2.1 Ensure password fields are not empty
      shell: >-
        cat /etc/shadow | awk -F: '($2 == "" ) { print $1 " does not have a password "}'
      register: suse_12_cis_6_2_1_out

    - name: 6.2.1 Ensure password fields are not empty | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_6_2_1"
        suse_12_cis_rule_expected_values:
          - ""
        suse_12_cis_rule_output: "{{ suse_12_cis_6_2_1_out }}"
  ignore_errors: true
  when: suse_12_cis_6_2_1 | bool

- name: 6.2.2
  block:
    - name: 6.2.2 Ensure no legacy "+" entries exist in /etc/passwd
      shell: grep '^\+:' /etc/passwd
      register: suse_12_cis_6_2_2_out

    - name: 6.2.2 Ensure no legacy "+" entries exist in /etc/passwd | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_6_2_2"
        suse_12_cis_rule_expected_values:
          - ""
        suse_12_cis_rule_output: "{{ suse_12_cis_6_2_2_out }}"
  ignore_errors: true
  when: suse_12_cis_6_2_2 | bool

- name: 6.2.3
  block:
    - name: 6.2.3 Ensure no legacy "+" entries exist in /etc/shadow
      shell: grep '^\+:' /etc/shadow
      register: suse_12_cis_6_2_3_out

    - name: 6.2.3 Ensure no legacy "+" entries exist in /etc/shadow | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_6_2_3"
        suse_12_cis_rule_expected_values:
          - ""
        suse_12_cis_rule_output: "{{ suse_12_cis_6_2_3_out }}"
  ignore_errors: true
  when: suse_12_cis_6_2_3 | bool

- name: 6.2.4
  block:
    - name: 6.2.4 Ensure no legacy "+" entries exist in /etc/group
      shell: grep '^\+:' /etc/group
      register: suse_12_cis_6_2_4_out

    - name: 6.2.4 Ensure no legacy "+" entries exist in /etc/group | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_6_2_4"
        suse_12_cis_rule_expected_values:
          - ""
        suse_12_cis_rule_output: "{{ suse_12_cis_6_2_4_out }}"
  ignore_errors: true
  when: suse_12_cis_6_2_4 | bool

- name: 6.2.5
  block:
    - name: 6.2.5 Ensure root is the only UID 0 account
      shell: >-
        cat /etc/passwd | awk -F: '($3 == 0) { print $1 }'
      register: suse_12_cis_6_2_5_out

    - name: 6.2.5 Ensure root is the only UID 0 account | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_6_2_5"
        suse_12_cis_rule_expected_values:
          - "root"
        suse_12_cis_rule_output: "{{ suse_12_cis_6_2_5_out }}"
  ignore_errors: true
  when: suse_12_cis_6_2_5 | bool

- name: 6.2.6
  block:
    - name: 6.2.6 Ensure root PATH Integrity
      script: suse_12_cis_6_2_6.sh
      register: suse_12_cis_6_2_6_out

    - name: 6.2.6 Ensure root PATH Integrity | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_6_2_6"
        suse_12_cis_rule_expected_values:
          - ""
        suse_12_cis_rule_output: "{{ suse_12_cis_6_2_6_out }}"
  ignore_errors: true
  when: suse_12_cis_6_2_6 | bool

- name: 6.2.7
  block:
    - name: 6.2.7 Ensure all users' home directories exist
      script: suse_12_cis_6_2_7.sh
      register: suse_12_cis_6_2_7_out

    - name: 6.2.7 Ensure all users' home directories exist | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_6_2_7"
        suse_12_cis_rule_expected_values:
          - ""
        suse_12_cis_rule_output: "{{ suse_12_cis_6_2_7_out }}"
  ignore_errors: true
  when: suse_12_cis_6_2_7 | bool

- name: 6.2.8
  block:
    - name: 6.2.8 Ensure users' home directories permissions are 750 or more restrictive
      script: suse_12_cis_6_2_8.sh
      register: suse_12_cis_6_2_8_out

    - name: 6.2.8 Ensure users' home directories permissions are 750 or more restrictive | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_6_2_8"
        suse_12_cis_rule_expected_values:
          - ""
        suse_12_cis_rule_output: "{{ suse_12_cis_6_2_8_out }}"
  ignore_errors: true
  when: suse_12_cis_6_2_8 | bool

- name: 6.2.9
  block:
    - name: 6.2.9 Ensure users own their home directories
      script: suse_12_cis_6_2_9.sh
      register: suse_12_cis_6_2_9_out

    - name: 6.2.9 Ensure users own their home directories | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_6_2_9"
        suse_12_cis_rule_expected_values:
          - ""
        suse_12_cis_rule_output: "{{ suse_12_cis_6_2_9_out }}"
  ignore_errors: true
  when: suse_12_cis_6_2_9 | bool

- name: 6.2.10
  block:
    - name: 6.2.10 Ensure users' dot files are not group or world writable
      script: suse_12_cis_6_2_10.sh
      register: suse_12_cis_6_2_10_out

    - name: 6.2.10 Ensure users' dot files are not group or world writable | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_6_2_10"
        suse_12_cis_rule_expected_values:
          - ""
        suse_12_cis_rule_output: "{{ suse_12_cis_6_2_10_out }}"
  ignore_errors: true
  when: suse_12_cis_6_2_10 | bool

- name: 6.2.11
  block:
    - name: 6.2.11 Ensure no users have .forward files
      script: suse_12_cis_6_2_11.sh
      register: suse_12_cis_6_2_11_out

    - name: 6.2.11 Ensure no users have .forward files | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_6_2_11"
        suse_12_cis_rule_expected_values:
          - ""
        suse_12_cis_rule_output: "{{ suse_12_cis_6_2_11_out }}"
  ignore_errors: true
  when: suse_12_cis_6_2_11 | bool

- name: 6.2.12
  block:
    - name: 6.2.12 Ensure no users have .netrc files
      script: suse_12_cis_6_2_12.sh
      register: suse_12_cis_6_2_12_out

    - name: 6.2.12 Ensure no users have .netrc files | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_6_2_12"
        suse_12_cis_rule_expected_values:
          - ""
        suse_12_cis_rule_output: "{{ suse_12_cis_6_2_12_out }}"
  ignore_errors: true
  when: suse_12_cis_6_2_12 | bool

- name: 6.2.13
  block:
    - name: 6.2.13 Ensure users' .netrc Files are not group or world accessible
      script: suse_12_cis_6_2_13.sh
      register: suse_12_cis_6_2_13_out

    - name: 6.2.13 Ensure users' .netrc Files are not group or world accessible | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_6_2_13"
        suse_12_cis_rule_expected_values:
          - ""
        suse_12_cis_rule_output: "{{ suse_12_cis_6_2_13_out }}"
  ignore_errors: true
  when: suse_12_cis_6_2_13 | bool

- name: 6.2.14
  block:
    - name: 6.2.14 Ensure no users have .rhosts files
      script: suse_12_cis_6_2_14.sh
      register: suse_12_cis_6_2_14_out

    - name: 6.2.14 Ensure no users have .rhosts files | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_6_2_14"
        suse_12_cis_rule_expected_values:
          - ""
        suse_12_cis_rule_output: "{{ suse_12_cis_6_2_14_out }}"
  ignore_errors: true
  when: suse_12_cis_6_2_14 | bool

- name: 6.2.15
  block:
    - name: 6.2.15 Ensure all groups in /etc/passwd exist in /etc/group
      script: suse_12_cis_6_2_15.sh
      register: suse_12_cis_6_2_15_out

    - name: 6.2.15 Ensure all groups in /etc/passwd exist in /etc/group | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_6_2_15"
        suse_12_cis_rule_expected_values:
          - ""
        suse_12_cis_rule_output: "{{ suse_12_cis_6_2_15_out }}"
  ignore_errors: true
  when: suse_12_cis_6_2_15 | bool

- name: 6.2.16
  block:
    - name: 6.2.16 Ensure no duplicate UIDs exist
      script: suse_12_cis_6_2_16.sh
      register: suse_12_cis_6_2_16_out

    - name: 6.2.16 Ensure no duplicate UIDs exist | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_6_2_16"
        suse_12_cis_rule_expected_values:
          - ""
        suse_12_cis_rule_output: "{{ suse_12_cis_6_2_16_out }}"
  ignore_errors: true
  when: suse_12_cis_6_2_16 | bool

- name: 6.2.17
  block:
    - name: 6.2.17 Ensure no duplicate GIDs exist
      script: suse_12_cis_6_2_17.sh
      register: suse_12_cis_6_2_17_out

    - name: 6.2.17 Ensure no duplicate GIDs exist | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_6_2_17"
        suse_12_cis_rule_expected_values:
          - ""
        suse_12_cis_rule_output: "{{ suse_12_cis_6_2_17_out }}"
  ignore_errors: true
  when: suse_12_cis_6_2_17 | bool

- name: 6.2.18
  block:
    - name: 6.2.18 Ensure no duplicate user names exist
      script: suse_12_cis_6_2_18.sh
      register: suse_12_cis_6_2_18_out

    - name: 6.2.18 Ensure no duplicate user names exist | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_6_2_18"
        suse_12_cis_rule_expected_values:
          - ""
        suse_12_cis_rule_output: "{{ suse_12_cis_6_2_18_out }}"
  ignore_errors: true
  when: suse_12_cis_6_2_18 | bool

- name: 6.2.19
  block:
    - name: 6.2.19 Ensure no duplicate group names exist
      script: suse_12_cis_6_2_19.sh
      register: suse_12_cis_6_2_19_out

    - name: 6.2.19 Ensure no duplicate group names exist | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_6_2_19"
        suse_12_cis_rule_expected_values:
          - ""
        suse_12_cis_rule_output: "{{ suse_12_cis_6_2_19_out }}"
  ignore_errors: true
  when: suse_12_cis_6_2_19 | bool

- name: 6.2.20
  block:
    - name: 6.2.20 Ensure shadow group is empty
      shell: "{{ item }}"
      loop:
        - >-
          grep ^shadow:[^:]*:[^:]*:[^:]+ /etc/group
        - >-
          awk -F: '($4 == "<shadow-gid>") { print }' /etc/passwd
      register: suse_12_cis_6_2_20_out

    - name: 6.2.20 Ensure shadow group is empty | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_6_2_20"
        suse_12_cis_rule_expected_values:
          - ""
          - ""
        suse_12_cis_rule_output: "{{ suse_12_cis_6_2_20_out }}"
  ignore_errors: true
  when: suse_12_cis_6_2_20 | bool