---
- name: 5.1.1
  block:
    - name: 5.1.1 Ensure cron daemon is enabled
      shell: systemctl is-enabled cron
      register: suse_12_cis_5_1_1_out

    - name: 5.1.1 Ensure cron daemon is enabled | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_5_1_1"
        suse_12_cis_rule_expected_values:
          - "enabled"
        suse_12_cis_rule_output: "{{ suse_12_cis_5_1_1_out }}"
  ignore_errors: true
  when: suse_12_cis_5_1_1 | bool

- name: 5.1.2
  block:
    - name: 5.1.2 Ensure permissions on /etc/crontab are configured
      shell: stat /etc/crontab -c "%a %U %G"
      register: suse_12_cis_5_1_2_out

    - name: 5.1.2 Ensure permissions on /etc/crontab are configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_5_1_2"
        suse_12_cis_rule_expected_values:
          - "600 root root"
        suse_12_cis_rule_output: "{{ suse_12_cis_5_1_2_out }}"
  ignore_errors: true
  when: suse_12_cis_5_1_2 | bool

- name: 5.1.3
  block:
    - name: 5.1.3 Ensure permissions on /etc/cron.hourly are configured
      shell: stat /etc/cron.hourly -c "%a %U %G"
      register: suse_12_cis_5_1_3_out

    - name: 5.1.3 Ensure permissions on /etc/cron.hourly are configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_5_1_3"
        suse_12_cis_rule_expected_values:
          - "700 root root"
        suse_12_cis_rule_output: "{{ suse_12_cis_5_1_3_out }}"
  ignore_errors: true
  when: suse_12_cis_5_1_3 | bool

- name: 5.1.4
  block:
    - name: 5.1.4 Ensure permissions on /etc/cron.daily are configured
      shell: stat /etc/cron.daily -c "%a %U %G"
      register: suse_12_cis_5_1_4_out

    - name: 5.1.4 Ensure permissions on /etc/cron.daily are configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_5_1_4"
        suse_12_cis_rule_expected_values:
          - "700 root root"
        suse_12_cis_rule_output: "{{ suse_12_cis_5_1_4_out }}"
  ignore_errors: true
  when: suse_12_cis_5_1_4 | bool

- name: 5.1.5
  block:
    - name: 5.1.5 Ensure permissions on /etc/cron.weekly are configured
      shell: stat /etc/cron.weekly -c "%a %U %G"
      register: suse_12_cis_5_1_5_out

    - name: 5.1.5 Ensure permissions on /etc/cron.weekly are configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_5_1_5"
        suse_12_cis_rule_expected_values:
          - "700 root root"
        suse_12_cis_rule_output: "{{ suse_12_cis_5_1_5_out }}"
  ignore_errors: true
  when: suse_12_cis_5_1_5 | bool

- name: 5.1.6
  block:
    - name: 5.1.6 Ensure permissions on /etc/cron.monthly are configured
      shell: stat /etc/cron.monthly -c "%a %U %G"
      register: suse_12_cis_5_1_6_out

    - name: 5.1.6 Ensure permissions on /etc/cron.monthly are configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_5_1_6"
        suse_12_cis_rule_expected_values:
          - "700 root root"
        suse_12_cis_rule_output: "{{ suse_12_cis_5_1_6_out }}"
  ignore_errors: true
  when: suse_12_cis_5_1_6 | bool

- name: 5.1.7
  block:
    - name: 5.1.7 Ensure permissions on /etc/cron.d are configured
      shell: stat /etc/cron.d -c "%a %U %G"
      register: suse_12_cis_5_1_7_out

    - name: 5.1.7 Ensure permissions on /etc/cron.d are configured | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_5_1_7"
        suse_12_cis_rule_expected_values:
          - "700 root root"
        suse_12_cis_rule_output: "{{ suse_12_cis_5_1_7_out }}"
  ignore_errors: true
  when: suse_12_cis_5_1_7 | bool