---
- name: 1.5.1
  block:
    - name: 1.5.1 Ensure core dumps are restricted
      shell: "{{ item }}"
      loop:
        - egrep "*\s+hard\s+core\s+0" /etc/security/limits.conf | awk '{$2=$2};1'
        - sysctl fs.suid_dumpable | sed -e 's/ //g'
        - grep "fs\.suid_dumpable" /etc/sysctl.conf | sed -e 's/ //g'
      register: suse_12_cis_1_5_1_out

    - name: 1.5.1 Ensure core dumps are restricted | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_1_5_1"
        suse_12_cis_rule_expected_values:
          - "* hard core 0"
          - "fs.suid_dumpable=0"
          - "fs.suid_dumpable=0"
        suse_12_cis_rule_output: "{{ suse_12_cis_1_5_1_out }}"
  ignore_errors: true
  when: suse_12_cis_1_5_1 | bool

- name: 1.5.3
  block:
    - name: 1.5.3 Ensure address space layout randomization (ASLR) is enabled
      shell: "{{ item }}"
      loop:
        - sysctl kernel.randomize_va_space | sed -e 's/ //g'
        - grep "kernel\.randomize_va_space" /etc/sysctl.conf | sed -e 's/ //g'
      register: suse_12_cis_1_5_3_out

    - name: 1.5.3 Ensure address space layout randomization (ASLR) is enabled | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_1_5_3"
        suse_12_cis_rule_expected_values:
          - kernel.randomize_va_space=2
          - kernel.randomize_va_space=2
        suse_12_cis_rule_output: "{{ suse_12_cis_1_5_3_out }}"
  ignore_errors: true
  when: suse_12_cis_1_5_3 | bool

- name: 1.5.4
  block:
    - name: 1.5.4 Ensure prelink is disabled
      shell: rpm -q prelink
      register: suse_12_cis_1_5_4_out

    - name: 1.5.4 Ensure prelink is disabled | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_1_5_4"
        suse_12_cis_rule_expected_values:
          - package prelink is not installed
        suse_12_cis_rule_output: "{{ suse_12_cis_1_5_4_out }}"
  ignore_errors: true
  when: suse_12_cis_1_5_4 | bool
