---
- name: 1.7.1.1
  block:
    - name: 1.7.1.1 Ensure message of the day is configured properly
      shell: "{{ item }}"
      loop:
        - cat /etc/motd
        - egrep '(\\v|\\r|\\m|\\s)' /etc/motd
      register: suse_12_cis_1_7_1_1_out

    - name: 1.7.1.1 Ensure message of the day is configured properly | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_1_7_1_1"
        suse_12_cis_rule_expected_values:
          - "{{ suse_12_cis_1_7_1_1_expected_value }}"
          - ""
        suse_12_cis_rule_output: "{{ suse_12_cis_1_7_1_1_out }}"
  ignore_errors: true
  when: suse_12_cis_1_7_1_1 | bool

- name: 1.7.1.2
  block:
    - name: 1.7.1.2 Ensure local login warning banner is configured properly
      shell: "{{ item }}"
      loop:
        - cat /etc/issue
        - egrep '(\\v|\\r|\\m|\\s)' /etc/issue
      register: suse_12_cis_1_7_1_2_out

    - name: 1.7.1.2 Ensure local login warning banner is configured properly | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_1_7_1_2"
        suse_12_cis_rule_expected_values:
          - "{{ suse_12_cis_1_7_1_2_expected_value }}"
          - ""
        suse_12_cis_rule_output: "{{ suse_12_cis_1_7_1_2_out }}"
  ignore_errors: true
  when: suse_12_cis_1_7_1_2 | bool

- name: 1.7.1.3
  block:
    - name: 1.7.1.3 Ensure remote login warning banner is configured properly
      shell: "{{ item }}"
      loop:
        - cat /etc/issue.net
        - egrep '(\\v|\\r|\\m|\\s)' /etc/issue.net
      register: suse_12_cis_1_7_1_3_out

    - name: 1.7.1.3 Ensure remote login warning banner is configured properly | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_1_7_1_3"
        suse_12_cis_rule_expected_values:
          - "{{ suse_12_cis_1_7_1_3_expected_value }}"
          - ""
        suse_12_cis_rule_output: "{{ suse_12_cis_1_7_1_3_out }}"
  ignore_errors: true
  when: suse_12_cis_1_7_1_3 | bool

