---
- name: 3.3.1
  block:
    - name: 3.3.1 Ensure IPv6 router advertisements are not accepted
      shell: "{{ item }}"
      loop:
        - sysctl net.ipv6.conf.all.accept_ra | sed -e 's/ //g'
        - sysctl net.ipv6.conf.default.accept_ra | sed -e 's/ //g'
        - grep "net\.ipv6\.conf\.all\.accept_ra" /etc/sysctl.conf | sed -e 's/ //g'
        - grep "net\.ipv6\.conf\.default\.accept_ra" /etc/sysctl.conf | sed -e 's/ //g'
      register: suse_12_cis_3_3_1_out

    - name: 3.3.1 Ensure IPv6 router advertisements are not accepted | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_3_3_1"
        suse_12_cis_rule_expected_values:
          - net.ipv6.conf.all.accept_ra=0
          - net.ipv6.conf.default.accept_ra=0
          - net.ipv6.conf.all.accept_ra=0
          - net.ipv6.conf.default.accept_ra=0
        suse_12_cis_rule_output: "{{ suse_12_cis_3_3_1_out }}"
  ignore_errors: true
  when: suse_12_cis_3_3_1 | bool

- name: 3.3.2
  block:
    - name: 3.3.2 Ensure IPv6 redirects are not accepted
      shell: "{{ item }}"
      loop:
        - sysctl net.ipv6.conf.all.accept_redirects | sed -e 's/ //g'
        - sysctl net.ipv6.conf.default.accept_redirects | sed -e 's/ //g'
        - grep "net\.ipv6\.conf\.all\.accept_redirect" /etc/sysctl.conf | sed -e 's/ //g'
        - grep "net\.ipv6\.conf\.default\.accept_redirect" /etc/sysctl.conf | sed -e 's/ //g'
      register: suse_12_cis_3_3_2_out

    - name: 3.3.2 Ensure IPv6 redirects are not accepted | Set Rule Values
      include_tasks: set_rule_values.yml
      vars:
        suse_12_cis_rule_key: "cis_3_3_2"
        suse_12_cis_rule_expected_values:
          - "net.ipv6.conf.all.accept_redirects=0"
          - "net.ipv6.conf.default.accept_redirects=0"
          - "net.ipv6.conf.all.accept_redirects=0"
          - "net.ipv6.conf.default.accept_redirects=0"
        suse_12_cis_rule_output: "{{ suse_12_cis_3_3_2_out }}"
  ignore_errors: true
  when: suse_12_cis_3_3_2 | bool
